config/routes.rb
ChecklistProcesos::Application.routes.draw do
  
  resources :rondas do
    resources :visita_diarias
  end

  resources :juzgados

  resources :ciudades

  devise_for :usuarios

  get "inicio/index"
  get "inicio/public" # Pagina de inicio a la que se le puede hacer cache
  
  root :to => 'inicio#index'

end

app/models/visita_diaria.rb
class VisitaDiaria < ActiveRecord::Base
  belongs_to :juzgado
  belongs_to :ronda
  attr_accessible :edictos, :estados, :fecha, :n_edictos, :n_estados, :n_traslados, :nada, :traslados, :juzgado_id, :notas
  validates :fecha, presence: {message: "no puede estar en blanco" }
  validates :juzgado_id, presence: {message: "no puede estar en blanco" }
end

app/controllers/visita_diarias_controller.rb
class VisitaDiariasController < ApplicationController
  before_filter :authenticate_usuario!
  # GET /rondas/1/visita_diarias
  # GET /rondas/1/visita_diarias.json
  def index
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diarias = @ronda.visita_diarias.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visita_diarias }
    end
  end

  # GET /ronda/1/visita_diarias/1
  # GET /ronda/1/visita_diarias/1.json
  def show
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diaria = VisitaDiaria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visita_diaria }
    end
  end

  # GET /ronda/1/visita_diarias/new
  # GET /ronda/1/visita_diarias/new.json
  def new
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diaria = @ronda.visita_diarias.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visita_diaria }
    end
  end

  # GET /ronda/1/visita_diarias/1/edit
  def edit
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diaria = VisitaDiaria.find(params[:id])
  end

  # POST /ronda/1/visita_diarias
  # POST /ronda/1/visita_diarias.json
  def create
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diaria = @ronda.visita_diarias.build(params[:visita_diaria])

    respond_to do |format|
      if @visita_diaria.save
        #format.html { redirect_to ronda_path(@ronda), notice: 'Visita diaria fue creada correctamente.' }
        format.html { redirect_to new_ronda_visita_diaria_path(@ronda), notice: 'Visita diaria fue creada correctamente.' }
        format.json { render json: @visita_diaria, status: :created, location: @visita_diaria }
      else
        format.html { render action: "new" }
        format.json { render json: @visita_diaria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ronda/1/visita_diarias/1
  # PUT /ronda/1/visita_diarias/1.json
  def update
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diaria = VisitaDiaria.find(params[:id])

    respond_to do |format|
      if @visita_diaria.update_attributes(params[:visita_diaria])
        format.html { redirect_to ronda_path(@ronda), notice: 'Visita diaria fue actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visita_diaria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ronda/1/visita_diarias/1
  # DELETE /ronda/1/visita_diarias/1.json
  def destroy
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:ronda_id])
    @visita_diaria = VisitaDiaria.find(params[:id])
    @visita_diaria.destroy

    respond_to do |format|
      format.html { redirect_to ronda_path(@ronda) }
      format.json { head :no_content }
    end
  end
end

app/helpers/visita_diarias_helper.rb
module VisitaDiariasHelper
end

app/views/visita_diarias/_form.html.erb
<%= form_for([@ronda, @visita_diaria]) do |f| %>
  <% if @visita_diaria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visita_diaria.errors.count, "error") %> evitó que la visita se guardara:</h2>

      <ul>
      <% @visita_diaria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain">
    <%= f.label :juzgado_id, class: :select %>
    <%= grouped_collection_select(:visita_diaria,:juzgado_id, Ciudad.all, :juzgados, :nombre, :id, :nombre_completo) %>
  </div>
  <div data-role="fieldcontain" >
    <%= f.label :n_estados, "Estados" %><br />
    <% tope_estados = @visita_diaria.n_estados > 5 ? @visita_diaria.n_estados : 5 %>
    <%= f.range_field :n_estados, in: 0..tope_estados %>
    <%= link_to "+", "#", id: :dup_rango_estados, "data-inline" => :true, "data-icon" => :plus, "data-iconpos" => :notext, "data-role" => :button %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :n_edictos, "Edictos" %><br />
    <% tope_edictos = @visita_diaria.n_edictos > 5 ? @visita_diaria.n_edictos : 5 %>
    <%= f.range_field :n_edictos, in: 0..tope_edictos %>
    <%= link_to "+", "#", id: :dup_rango_edictos, "data-inline" => :true, "data-icon" => :plus, "data-iconpos" => :notext, "data-role" => :button %>

  </div>
  <div data-role="fieldcontain">
    <%= f.label :n_traslados, "Traslados" %><br />
    <% tope_traslados = @visita_diaria.n_traslados > 5 ? @visita_diaria.n_traslados : 5 %>
    <%= f.range_field :n_traslados, in: 0..tope_traslados %>
    <%= link_to "+", "#", id: :dup_rango_traslados, "data-inline" => :true, "data-icon" => :plus, "data-iconpos" => :notext, "data-role" => :button %>

  </div>
  <div data-role="fieldcontain">
  	<fieldset data-role="controlgroup">
    	<%= f.check_box :nada %>
    	<%= f.label :nada %>
    </fieldset>
  </div>
  <div data-role="fieldcontain" class="ui-hide-label">
    <%= f.label :notas %><br />
    <%= f.text_area :notas, placeholder: "Notas" %>
  </div>
  
  <div class="actions">
    <%= f.submit "Aceptar" %>
  </div>
  <div data-role="fieldcontain" >
  	<fieldset data-role="controlgroup" data-type="horizontal">
    	<legend >Fecha</legend>
    	<%= f.date_select :fecha %>
    </fieldset>
  </div>
<% end %>

app/views/visita_diarias/edit.html.erb
<% provide :header_left, link_to('Atrás', ronda_visita_diarias_path) %>
<% provide :header_title, "Editar Visita Diaria"%>
<% provide :header_right, link_to('Ver', ronda_visita_diaria_path(@ronda, @visita_diaria)) %>

<%= render 'form' %>

<%= link_to 'Eliminar', ronda_visita_diaria_path(@ronda, @visita_diaria), method: :delete, "data-role" => :button, "data-icon" => :delete, data: { confirm: '¿Seguro desea eliminar la visita?' } %>

app/views/visita_diarias/index.html.erb
<% provide :header_left, link_to('Atrás', ronda_path(@ronda)) %>
<% provide :header_title, "Visitas" %>
<% provide :header_right, link_to('Agregar',  new_ronda_visita_diaria_path(@ronda), "data-icon" => :plus, class: "ui-btn-right") %>

<ul data-role="listview" data-inset="true" >
<% @visita_diarias.each do |visita_diaria| %>
	<li><%= link_to visita_diaria.juzgado.nombre_completo, ronda_visita_diaria_path(@ronda, visita_diaria) %></li>
<% end %>
</ul>

app/views/visita_diarias/new.html.erb
<% provide :header_left, link_to('Atrás', ronda_path(@ronda)) %>
<% provide :header_title, "Agregar Visita Diaria"%>

<%= render 'form' %>

app/views/visita_diarias/show.html.erb
<% provide :header_left, link_to('Atrás', ronda_path(@visita_diaria.ronda)) %>
<% provide :header_title, "Ver Visita Diaria"%>
<% provide :header_right, link_to('Editar', edit_ronda_visita_diaria_path(@visita_diaria.ronda, @visita_diaria)) %>
<ul data-role="listview" data-inset="true" >
	<li>
	  <b>Juzgado:</b>
	  <%= @visita_diaria.juzgado.nombre_completo %>
	</li>
	
	<li>
	  <b>N estados:</b>
	  <%= @visita_diaria.n_estados %>
	</li>
	
	<li>
	  <b>N edictos:</b>
	  <%= @visita_diaria.n_edictos %>
	</li>
	
	<li>
	  <b>N traslados:</b>
	  <%= @visita_diaria.n_traslados %>
	</li>
	
	<% if @visita_diaria.nada %>
		<li data-theme="b">
		  <b>Nada:</b> NO SALIÓ NADA HOY
		  	
	<% else %>
		<li>
	  		<b>Nada:</b>
		  	<%= @visita_diaria.nada %>
		  	
		  
	<% end %>
		</li>
	<li>
		<b>Notas:</b>
		<%= @visita_diaria.notas %>
	</li>
	<li>
	  <b>Fecha:</b>
	  <%= @visita_diaria.fecha %>
	</li>
</ul>