config/routes.rb
ChecklistProcesos::Application.routes.draw do
  
  resources :rondas do
    resources :visita_diarias
  end

  resources :juzgados

  resources :ciudades

  devise_for :usuarios

  get "inicio/index"
  get "inicio/public" # Pagina de inicio a la que se le puede hacer cache
  
  root :to => 'inicio#index'

end

app/models/ronda.rb
class Ronda < ActiveRecord::Base
  belongs_to :usuario
  has_many :visita_diarias
  attr_accessible :fecha
  validates :fecha, presence: {message: "no puede estar en blanco" }
end

app/controllers/rondas_controller.rb
class RondasController < ApplicationController
  before_filter :authenticate_usuario!
  # GET /rondas
  # GET /rondas.json
  def index
    seleccionarMenu(:rondas)
    @rondas = Ronda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rondas }
    end
  end

  # GET /rondas/1
  # GET /rondas/1.json
  def show
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ronda }
    end
  end

  # GET /rondas/new
  # GET /rondas/new.json
  def new
    seleccionarMenu(:rondas)
    @ronda = current_usuario.rondas.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ronda }
    end
  end

  # GET /rondas/1/edit
  def edit
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:id])
  end

  # POST /rondas
  # POST /rondas.json
  def create
    seleccionarMenu(:rondas)
    @ronda = current_usuario.rondas.build(params[:ronda])

    respond_to do |format|
      if @ronda.save
        format.html { redirect_to @ronda, notice: 'Ronda creada satisfactoriamente.' }
        format.json { render json: @ronda, status: :created, location: @ronda }
      else
        format.html { render action: "new" }
        format.json { render json: @ronda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rondas/1
  # PUT /rondas/1.json
  def update
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:id])

    respond_to do |format|
      if @ronda.update_attributes(params[:ronda])
        format.html { redirect_to @ronda, notice: 'Ronda actualizada satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ronda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rondas/1
  # DELETE /rondas/1.json
  def destroy
    seleccionarMenu(:rondas)
    @ronda = Ronda.find(params[:id])
    @ronda.destroy

    respond_to do |format|
      format.html { redirect_to rondas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rondas_helper.rb
module RondasHelper
end

app/views/rondas/_form.html.erb
<%= form_for(@ronda) do |f| %>
  <% if @ronda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ronda.errors.count, "error") %> evitó que se guardara la ronda:</h2>

      <ul>
      <% @ronda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" >
    <fieldset data-role="controlgroup" data-type="horizontal">
    	<legend >Fecha</legend>
    	<%= f.date_select :fecha %>
    </fieldset>
  </div>
  <div class="actions">
    <%= f.submit "Aceptar" %>
  </div>
<% end %>

app/views/rondas/edit.html.erb
<% provide :header_left, link_to('Atrás', rondas_path) %>
<% provide :header_title, "Editar Ronda"%>
<% provide :header_right, link_to('Ver', @ronda) %>

<%= render 'form' %>

<%= link_to 'Eliminar', @ronda, method: :delete, "data-role" => :button, "data-icon" => :delete, data: { confirm: '¿Seguro que desea borrar la ronda?' } %>

app/views/rondas/index.html.erb
<% provide :header_title, "Rondas" %>
<% provide :header_right, link_to('Agregar', new_ronda_path, "data-icon" => :plus, class: "ui-btn-right") %>

<ul data-role="listview">
<% @rondas.each do |ronda| %>
    <li><%= link_to "#{ronda.fecha} por #{ronda.usuario.email}", ronda %></li>
<% end %>
</ul>

app/views/rondas/new.html.erb
<% provide :header_left, link_to('Atrás', rondas_path) %>
<% provide :header_title, "Agregar Ronda"%>

<%= render 'form' %>

app/views/rondas/show.html.erb
<% provide :header_left, link_to('Atrás', rondas_path) %>
<% provide :header_title, "Ver Ronda"%>
<% provide :header_right, link_to('Editar', edit_ronda_path(@ronda)) %>
<ul data-role="listview" data-inset="true" >
	<li>
	  <b>Fecha:</b>
	  <%= @ronda.fecha %>
	</li>
	
	<li>
	  <b>Usuario:</b>
	  <%= @ronda.usuario.email %>
	</li>
</ul>
<%= link_to 'Nueva Visita', new_ronda_visita_diaria_path(@ronda), "data-role" => :button %>
<hr />
<% if @ronda.visita_diarias.any? %>
	<h3>Visitas</h3>
	<ul data-role="listview" data-inset="true" >
	<% @ronda.visita_diarias.order(:juzgado_id).each do |v| %>
		<li><%= link_to v.juzgado.nombre_completo, ronda_visita_diaria_path(@ronda, v) %></li>
	<% end %>
	</ul>
<% end %>