config/routes.rb
ChecklistProcesos::Application.routes.draw do
  
  resources :rondas do
    resources :visita_diarias
  end

  resources :juzgados

  resources :ciudades

  devise_for :usuarios

  get "inicio/index"
  get "inicio/public" # Pagina de inicio a la que se le puede hacer cache
  
  root :to => 'inicio#index'

end

app/models/juzgado.rb
class Juzgado < ActiveRecord::Base
  belongs_to :ciudad
  has_many :visita_diarias
  attr_accessible :direccion, :nombre, :ciudad_id
  validates :nombre, presence: {message: "No puede estar en blanco" } #Solo es obligatorio el nombre.
  validates :ciudad_id, presence: {message: "Debe escoger una" }
  
  def nombre_completo #Me devuelve el nombre completo del juzgado para evitar hacer interpolacion de strings en otros lados.
    if nombre == "Tribunal Contencioso Administrativo de Risaralda"
      nombre
    else
      "#{nombre} de #{ciudad.nombre}"
    end
  end
end

app/controllers/juzgados_controller.rb
class JuzgadosController < ApplicationController
  before_filter :authenticate_usuario!
  # GET /juzgados
  # GET /juzgados.json
  def index
    seleccionarMenu(:juzgados)
    @juzgados = Juzgado.order(:ciudad_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @juzgados }
    end
  end

  # GET /juzgados/1
  # GET /juzgados/1.json
  def show
    seleccionarMenu(:juzgados)
    @juzgado = Juzgado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @juzgado }
    end
  end

  # GET /juzgados/new
  # GET /juzgados/new.json
  def new
    seleccionarMenu(:juzgados)
    @juzgado = Juzgado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @juzgado }
    end
  end

  # GET /juzgados/1/edit
  def edit
    seleccionarMenu(:juzgados)
    @juzgado = Juzgado.find(params[:id])
  end

  # POST /juzgados
  # POST /juzgados.json
  def create
    seleccionarMenu(:juzgados)
    @juzgado = Juzgado.new(params[:juzgado])

    respond_to do |format|
      if @juzgado.save
        format.html { redirect_to @juzgado, notice: 'Juzgado fue creado satisfactoriamente.' }
        format.json { render json: @juzgado, status: :created, location: @juzgado }
      else
        format.html { render action: "new" }
        format.json { render json: @juzgado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /juzgados/1
  # PUT /juzgados/1.json
  def update
    seleccionarMenu(:juzgados)
    @juzgado = Juzgado.find(params[:id])

    respond_to do |format|
      if @juzgado.update_attributes(params[:juzgado])
        format.html { redirect_to @juzgado, notice: 'Juzgado fue actualizado satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @juzgado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juzgados/1
  # DELETE /juzgados/1.json
  def destroy
    seleccionarMenu(:juzgados)
    @juzgado = Juzgado.find(params[:id])
    @juzgado.destroy

    respond_to do |format|
      format.html { redirect_to juzgados_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/juzgados_helper.rb
module JuzgadosHelper
end

app/views/juzgados/_form.html.erb
<%= form_for(@juzgado) do |f| %>
  <% if @juzgado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@juzgado.errors.count, "error") %> no permitió que este juzgado fuera guardado:</h2>

      <ul>
      <% @juzgado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" class="ui-hide-label">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre, placeholder: "Nombre" %>
  </div>
  <div data-role="fieldcontain" class="ui-hide-label">
    <%= f.label :direccion, "Dirección" %><br />
    <%= f.text_field :direccion, placeholder: "Dirección" %>
  </div>
  <div data-role="fieldcontain">
  	<%= f.label :ciudad_id, class: :select %>
 	<%= collection_select(:juzgado, :ciudad_id, Ciudad.all, :id, :nombre) %>
  </div>
  <div class="actions">
    <%= f.submit "Aceptar"  %>
  </div>
<% end %>

app/views/juzgados/edit.html.erb
<% provide :header_left, link_to('Atrás', juzgados_path) %>
<% provide :header_title, "Editar Juzgado"%>
<% provide :header_right, link_to('Ver', @juzgado) %>

<%= render 'form' %>

<%= link_to 'Eliminar', @juzgado, method: :delete, "data-role" => :button, "data-icon" => :delete, data: { confirm: '¿Segurito segurito?' } %>

app/views/juzgados/index.html.erb
<% provide :header_title, "Juzgados" %>
<% provide :header_right, link_to('Agregar', new_juzgado_path, "data-icon" => :plus, class: "ui-btn-right") %>

<ul data-role="listview">
<% @juzgados.each do |juzgado| %>
    <li><%= link_to juzgado.nombre_completo, juzgado %></li>
<% end %>
</ul>

app/views/juzgados/new.html.erb
<% provide :header_left, link_to('Atrás', juzgados_path) %>
<% provide :header_title, "Agregar Juzgado"%>

<%= render 'form' %>

app/views/juzgados/show.html.erb
<% provide :header_left, link_to('Atrás', juzgados_path) %>
<% provide :header_title, "Ver Juzgado"%>
<% provide :header_right, link_to('Editar', edit_juzgado_path(@juzgado)) %>
<ul data-role="listview" data-inset="true">
	<li>
	  <b>Nombre:</b>
	  <%= @juzgado.nombre %>
	</li>
	
	<li>
	  <b>Dirección:</b>
	  <%= @juzgado.direccion %>
	</li>
	
	<li>
	  <b>Ciudad:</b>
	  <%= @juzgado.ciudad.nombre %>
	</li>
</ul>