config/routes.rb
ChecklistProcesos::Application.routes.draw do
  
  resources :rondas do
    resources :visita_diarias
  end

  resources :juzgados

  resources :ciudades

  devise_for :usuarios

  get "inicio/index"
  get "inicio/public" # Pagina de inicio a la que se le puede hacer cache
  
  root :to => 'inicio#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChecklistProcesos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-mobile/1.3.2/demos/css/themes/default/jquery.mobile-1.3.2.min.css" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-mobile/1.3.2/jquery.mobile.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
</head>
<body>
	<div data-role="page" >
		<div data-role="header">
			<%= yield :header_left %>
			<h1><%= yield :header_title %></h1>
			<%= yield :header_right %>
		</div>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		
		<%= yield %>
		
		<div data-role="footer" data-position="fixed">
			<% if usuario_signed_in? %>
				<div data-role="navbar">
					<ul>
						<li><%= link_to "Rondas", rondas_path, class: menuseleccionado == :rondas ? ' ui-btn-active ui-state-persist' : '' %></li>
						<li><%= link_to "Juzgados", juzgados_path, class: menuseleccionado == :juzgados ? ' ui-btn-active ui-state-persist' : '' %></li>
						<li><%= link_to "Ciudades", ciudades_path, class: menuseleccionado == :ciudades ? ' ui-btn-active ui-state-persist' : '' %></li>
						<li><%= link_to "Salir", destroy_usuario_session_path, method: :delete %></li>
					</ul>
				</div>
			<% else %>
				<%= link_to "Iniciar Sesión", new_usuario_session_path, "data-role" => :button %>
			<% end %>
		</div>
	</div>
</body>
</html>